spring:
  application:
    name: News Feed Scraper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

crawl:
  cron-expression: "0 0 0 * * *"
  sources:
    - name: Yahoo
      url: https://finance.yahoo.com/news
      target-article-count: 40
      start-point-xPath: //*[@id="Fin-Stream"]/ul/li
      has-context-json: true
      article-element: article
      origin-xPath: //*[@class="caas-logo"]/a
      title-xPath: //*[@class="caas-title-wrapper"]/h1
      author-xPath: //*[@class="caas-author-byline-collapse"]
      date-xPath: //*[@class="caas-attr-time-style"]/time
      valid-link-formats: /news/, https://finance.yahoo.com/news
      image-xPath: //*[@class="caas-img-container"]//*[@class="caas-img"]

---
spring:
  config:
    activate:
      on-profile: local

crawl:
  cron-expression: "0 * * * * *"
